import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"; 
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yun Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* ThemeProvider로 전체를 감싸줍니다. */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-3xl mx-auto px-4">
            <header>
              {/* 여기에 나중에 헤더/내비게이션 바를 추가합니다. */}
            </header>
            <main>{children}</main>
            <footer>
              {/* 여기에 나중에 푸터를 추가합니다. */}
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}