import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/Header"; // Header 컴포넌트 import

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yun Blog",
  description: "Generated by create next app",
  icons: {
    icon: "/yun-blog/y.svg",
    apple: "/yun-blog/y.svg",
    shortcut: "/yun-blog/y.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-3xl mx-auto px-4">
            <Header />
            <main>{children}</main>
            <footer className="text-center text-muted-foreground py-8">
              © {new Date().getFullYear()} Yun Blog. All rights reserved.
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}